---
- name: Install Podman
  include: Podman_Install.yml
  when: Container_Runner == "Podman"

- name: deploy containers
  loop: "{{ PodmanContainers }}"
  include_tasks: "Containers/{{ item }}/{{ item }}.yml"
