---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: ghcr.io/linuxserver/jackett:latest
    ports:
      - 9117:9117
    env:
      PGID="{{ GroupID }}"
      PUID="{{ UserID }}"
      TZ="{{ TimeZone}}"
    volume:
      - "/{{ ContainerData }}/{{ item }}/Config:/config:rw"
      - "/{{ ContainerData }}/{{ item }}/Downloads:/downloads:rw"
  register: state
  
- name: Make {{ item }} Systemd service
  shell: cd /etc/systemd/system/ && podman generate systemd --files --name {{ item }}
  when: state.changed == true

- name: Pause for 10 seconds to start app
  pause:
    seconds: 10
  when: state.changed == true


- name: restart {{ item }} service if change
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == true

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == false
