---
- name: Create {{ item }} Podman Container
  containers.podman.podman_container:
    name: "{{ item }}"
    image: ghcr.io/linuxserver/transmission:latest
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    env:
      PUID="{{ UserID }}"
      PGID="{{ UserID }}"
      TZ="{{ TimeZone }}"
      USER="{{ Transmission_User }}"
      PASS="{{ Transmission_Password }}"
    volume:
      - "/{{ ContainerData }}/{{ item }}/Config:/config:rw"
      - "/{{ ContainerData }}/{{ item }}/Downloads:/downloads:rw"
      - "/{{ ContainerData }}/{{ item }}/Watch:/watch:rw"

  register: state

#podman generate systemd --files --name Wordpress 
#Auto Generate systemd files
# cd ~/.config/systemd/user && /usr/bin/podman generate systemd --files --name {{ item }}
- name: Make {{ item }} Systemd service
  shell: cd /etc/systemd/system && podman generate systemd --files --name {{ item }}
  when: state.changed == true

- name: restart {{ item }} service if change
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == true

- name: Start {{ item }} service
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: "container-{{ item }}"
  when: state.changed == false